name: Build for Mystrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository with Submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build Matrix OS
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.3.1
        target: esp32s3
        path: '.'
        command: make DEVICE=Mystrix fullclean build-nightly uf2

    - name: Get Commit Info
      id: commit_info
      run: |
        echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Rename UF2 File
      run: |
        OLD_FILENAME="build/Mystrix/MatrixOS-Mystrix.uf2"
        NEW_FILENAME="build/Mystrix/MatrixOS-Mystrix-nightly-${{ env.CURRENT_DATE }}-${{ env.COMMIT_HASH }}.uf2"
        sudo chown -R $(whoami):$(whoami) build/
        sudo chmod -R 755 build/
        cp "$OLD_FILENAME" "$NEW_FILENAME"
        echo "NEW_FILENAME=$NEW_FILENAME" >> $GITHUB_ENV
        echo "Renamed to: $NEW_FILENAME"

    - name: Upload UF2 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MatrixOS-Mystrix-nightly-${{ env.CURRENT_DATE }}-${{ env.COMMIT_HASH }}
        path: ${{ env.NEW_FILENAME }}
        if-no-files-found: error
